export const MOCKUP_DATA = [
  {
    id: 1,
    language: "Python",
    type: "컴파일 문제",
    title: "리스트 평균 계산",
    description:
      "정수 리스트를 입력받아 평균을 출력하는 프로그램을 작성하세요.",
    input: "입력은 공백으로 구분된 정수 리스트",
    output: "리스트 평균을 소수점 2자리까지 출력",
    example_input: "입력: 1 2 3 4",
    example_output: "출력: 2.50",
    solution:
      "nums = list(map(int, input().split()))\nprint(f'{sum(nums) / len(nums):.2f}')",
  },
  {
    id: 2,
    language: "Python",
    type: "컴파일 문제",
    title: "문자열 대문자 변환",
    description: "문자열을 입력받아 모두 대문자로 변환한 결과를 출력하세요.",
    input: "입력은 소문자 또는 혼합된 문자열",
    output: "대문자로 변환된 문자열 출력",
    example_input: "입력: hello",
    example_output: "출력: HELLO",
    solution: "text = input()\nprint(text.upper())",
  },
  {
    id: 3,
    language: "Python",
    type: "컴파일 문제",
    title: "삼각형의 넓이 계산",
    description: "밑변과 높이를 입력받아 삼각형의 넓이를 계산하세요.",
    input: "입력은 공백으로 구분된 두 정수(밑변, 높이)",
    output: "삼각형의 넓이를 출력",
    example_input: "입력: 4 5",
    example_output: "출력: 10.0",
    solution:
      "base, height = map(int, input().split())\narea = 0.5 * base * height\nprint(f'{area:.1f}')",
  },
  {
    id: 4,
    language: "Python",
    type: "컴파일 문제",
    title: "짝수 합 계산",
    description: "1부터 N까지의 짝수 합을 계산하는 프로그램을 작성하세요.",
    input: "입력은 1 이상의 정수 N",
    output: "1부터 N까지 짝수의 합 출력",
    example_input: "입력: 10",
    example_output: "출력: 30",
    solution: "N = int(input())\nprint(sum(i for i in range(2, N + 1, 2)))",
  },
  {
    id: 5,
    language: "Python",
    type: "컴파일 문제",
    title: "두 문자열 연결",
    description: "두 개의 문자열을 입력받아 연결된 결과를 출력하세요.",
    input: "입력은 공백으로 구분된 두 문자열",
    output: "두 문자열이 연결된 결과 출력",
    example_input: "입력: Hello World",
    example_output: "출력: HelloWorld",
    solution: "str1, str2 = input().split()\nprint(str1 + str2)",
  },
  {
    id: 6,
    language: "Python",
    type: "컴파일 문제",
    title: "리스트에서 특정 값 찾기",
    description:
      "정수 리스트에서 특정 값을 찾고, 해당 값이 존재하면 위치를 출력하세요.",
    input: "입력은 정수 리스트와 찾고자 하는 값",
    output: "값의 위치를 출력, 없으면 -1 출력",
    example_input: "입력: 1 2 3 4 3",
    example_output: "출력: 2",
    solution:
      "nums = list(map(int, input().split()))\ntarget = int(input())\nprint(nums.index(target) if target in nums else -1)",
  },
  {
    id: 7,
    language: "Python",
    type: "컴파일 문제",
    title: "피보나치 수열 출력",
    description: "N번째 피보나치 수를 출력하는 프로그램을 작성하세요.",
    input: "입력은 1 이상의 정수 N",
    output: "N번째 피보나치 수 출력",
    example_input: "입력: 5",
    example_output: "출력: 5",
    solution:
      "def fibonacci(n):\n    if n <= 1:\n        return n\n    else:\n        return fibonacci(n-1) + fibonacci(n-2)\n\nN = int(input())\nprint(fibonacci(N))",
  },
  {
    id: 8,
    language: "Python",
    type: "컴파일 문제",
    title: "리스트에서 중복 제거",
    description: "정수 리스트에서 중복을 제거하고 정렬된 결과를 출력하세요.",
    input: "입력은 공백으로 구분된 정수 리스트",
    output: "중복이 제거된 정렬된 리스트 출력",
    example_input: "입력: 4 2 4 3 3",
    example_output: "출력: [2, 3, 4]",
    solution:
      "nums = list(map(int, input().split()))\nprint(sorted(set(nums)))",
  },
  {
    id: 9,
    language: "Python",
    type: "컴파일 문제",
    title: "단어 개수 세기",
    description: "문자열에서 공백으로 구분된 단어의 개수를 출력하세요.",
    input: "입력은 공백이 포함된 문자열",
    output: "단어의 개수를 출력",
    example_input: "입력: This is a test",
    example_output: "출력: 4",
    solution: "text = input()\nprint(len(text.split()))",
  },
  {
    id: 10,
    language: "Python",
    type: "컴파일 문제",
    title: "입력 숫자 역순 출력",
    description: "정수를 입력받아 자리수를 역순으로 출력하세요.",
    input: "입력은 1 이상의 정수",
    output: "역순으로 정렬된 숫자 출력",
    example_input: "입력: 12345",
    example_output: "출력: 54321",
    solution: "number = input()\nprint(number[::-1])",
  },
  {
    id: 11,
    language: "Python",
    type: "정답 요구 문제",
    title: "두 수의 합 계산",
    description: "두 정수를 입력받아 합을 계산하세요.",
    input: "입력은 두 정수 (3, 7)",
    output: "두 수의 합 출력",
    example_input: "입력: 3 7",
    example_output: "출력: 10",
    solution: "a, b = map(int, input().split())\nprint(a + b)",
  },
  {
    id: 12,
    language: "Python",
    type: "정답 요구 문제",
    title: "숫자 비교",
    description: "두 숫자를 비교하여 더 큰 숫자를 출력하세요.",
    input: "입력은 두 정수 (3, 7)",
    output: "더 큰 숫자 출력",
    example_input: "입력: 3 7",
    example_output: "출력: 7",
    solution: "a, b = map(int, input().split())\nprint(max(a, b))",
  },
  {
    id: 13,
    language: "Python",
    type: "정답 요구 문제",
    title: "구구단 5단 출력",
    description: "구구단의 5단을 출력하세요.",
    input: "입력 없음",
    output: "5단의 결과를 출력",
    example_input: "입력: 없음",
    example_output: "출력: 5 10 ... 45",
    solution: "for i in range(1, 10):\n    print(f'5 * {i} = {5 * i}')",
  },
  {
    id: 14,
    language: "Python",
    type: "정답 요구 문제",
    title: "짝수 홀수 구분",
    description: "입력된 수가 짝수인지 홀수인지 출력하세요.",
    input: "입력은 정수 (3)",
    output: "홀수 또는 짝수 출력",
    example_input: "입력: 3",
    example_output: "출력: 홀수",
    solution: "num = int(input())\nprint('짝수' if num % 2 == 0 else '홀수')",
  },
  {
    id: 15,
    language: "Python",
    type: "정답 요구 문제",
    title: "1부터 N까지 합",
    description: "1부터 N까지의 합을 출력하세요.",
    input: "입력은 정수 N (5)",
    output: "1부터 N까지 합 출력",
    example_input: "입력: 5",
    example_output: "출력: 15",
    solution: "N = int(input())\nprint(sum(range(1, N + 1)))",
  },
  {
    id: 16,
    language: "Python",
    type: "정답 요구 문제",
    title: "최대값 찾기",
    description: "주어진 리스트에서 최대값을 출력하세요.",
    input: "입력은 리스트 [3, 7, 2]",
    output: "리스트의 최대값 출력",
    example_input: "입력: [3, 7, 2]",
    example_output: "출력: 7",
    solution: "nums = list(map(int, input().split()))\nprint(max(nums))",
  },
  {
    id: 17,
    language: "Python",
    type: "정답 요구 문제",
    title: "평균 구하기",
    description: "주어진 리스트의 평균을 구하세요.",
    input: "입력은 리스트 [4, 6]",
    output: "리스트의 평균 출력",
    example_input: "입력: [4, 6]",
    example_output: "출력: 5.0",
    solution:
      "nums = list(map(int, input().split()))\nprint(sum(nums) / len(nums))",
  },
  {
    id: 18,
    language: "Python",
    type: "정답 요구 문제",
    title: "팩토리얼 구하기",
    description: "주어진 정수의 팩토리얼을 구하세요.",
    input: "입력은 정수 5",
    output: "팩토리얼 출력",
    example_input: "입력: 5",
    example_output: "출력: 120",
    solution:
      "n = int(input())\nfact = 1\nfor i in range(1, n + 1):\n    fact *= i\nprint(fact)",
  },
  {
    id: 19,
    language: "Python",
    type: "정답 요구 문제",
    title: "리스트 정렬",
    description: "주어진 리스트를 오름차순으로 정렬하세요.",
    input: "입력은 리스트 [4, 2, 3, 1]",
    output: "오름차순 정렬 출력",
    example_input: "입력: [4, 2, 3, 1]",
    example_output: "출력: [1, 2, 3, 4]",
    solution: "nums = list(map(int, input().split()))\nprint(sorted(nums))",
  },
  {
    id: 20,
    language: "Python",
    type: "정답 요구 문제",
    title: "문자열 뒤집기",
    description: "주어진 문자열을 뒤집어서 출력하세요.",
    input: "입력은 문자열 'Hello'",
    output: "뒤집힌 문자열 출력",
    example_input: "입력: 'Hello'",
    example_output: "출력: 'olleH'",
    solution: "text = input()\nprint(text[::-1])",
  },
];
